### ISSUE TITLE
RGB Color Picker not correctly displayed (Google search)

### ISSUE THREAD

**Issue by MarcDirven** [belaviyo/dark-theme#17]
The slider and the current color are not correctly dispalyed. It also appears to be missing some borders around the color picker color information.

See images below.

With dark mode enabled (obviously)

![](https://i.imgur.com/25YuFku.png)

With dark mode disabled.

![](https://i.imgur.com/LISJ0Wo.png)

**Comment by belaviyo** [comment]
Should be fixed by 0.3.0 release. You can try in on FF for now. Thanks for the report.
