### ISSUE TITLE
Chrome Web Store not among supported Google products/services

### ISSUE THREAD

**Issue by geoffc86** [belaviyo/dark-theme#31]
Somewhat self-evident from the title. Went to leave a positive review after verifying that it works for me on Search, Translate, and Photos, and found the stark white still blaring at me. Relatively minor concern, but one of which I felt you should be aware.

**Comment by belaviyo** [comment]
This is not doable. WebStore is a protected hostname on Chromium browsers to prevent malicious extensions from altering its content. So no extension can interact with this hostname.
