### ISSUE TITLE
Google Maps web results are transparent over map

### ISSUE THREAD

**Issue by xyphur** [belaviyo/dark-theme#4]
As the title says, the area where details about a specific search result are displayed is transparent.

The dark theme color can be seen under this area briefly when zooming out the map, until the map tiles load and fill the space in again.

Screenshot attached.
![google maps dark theme issue](https://user-images.githubusercontent.com/47288155/52172394-54753800-273c-11e9-9f48-9a0434b18bce.png)

**Comment by xyphur** [comment]
Hi, no problem. To reproduce, search google for anything that would likely have a map result, such as a fast food restaurant ("Subway" for example). In the Google search results will be a map image with an alphabetically ordered list of locations under it. If you click one of those, you get a map-enhanced search results page that isn't the same as the actual Google Maps site, it's more of a map-based search results page that brings up a contextual info card for the result you clicked on originally. This is the area that is transparent in the above screenshot. Hope that helps. I'd provide a link, but the link doesn't have a copy option when right-clicked, likely a script of some sort I guess...

Something else of note, perhaps related, the search box in Google results that floats when you scroll the results page is also transparent resulting in it being lost in the search results text. I think the box should probably be the same color as the page background with a partial opacity to appear slightly transparent (if this is even possible, I'm not sure), or not transparent at all (safe option).

**Comment by belaviyo** [comment]
Thanks! The new release has a better support for embedded items like the one that you have reported. Still some bugs though.

**Comment by xyphur** [comment]
Looks good so far! My issue with Google maps seems to be resolved. Thanks!

I did notice another issue, but it's with the Facebook version of the add-on. I'll write up a quick post with a screenshot and post it to the correct section later when I'm home.
