### ISSUE TITLE
dark-theme for opera 57.0.3098.116 don't work

### ISSUE THREAD

**Issue by BigBadSheep** [belaviyo/dark-theme#5]
dark-theme for opera 57.0.3098.116 don't work.
I tryed to reset it but still don't work

**Comment by AlbertoP64** [comment]
Enabled the second check permission for the extension?
It works ONLY after doing the following:

<> 1 - GO TO OPERA EXTENSIONS MANAGING PAGE (upper left "O" menu -> Extensions -> Extensions).
<> 2 - scroll until seeing the "Dark Theme for Google" extension
<> 3 - check the SECOND CHECKBOX "consent access to search results" for this extension.

Then the extension do work immediately!!
