### ISSUE TITLE
Chrome desktop tweaks and fixes

### ISSUE THREAD

**Issue by FreddieDev** [belaviyo/dark-theme#8]
The Google "apps" button shows up black, this can be fixed easily with CSS invert filter:
filter: invert(1);
![image](https://user-images.githubusercontent.com/4047565/55953367-d52c4500-5c53-11e9-9249-35204a5233b8.png)

Additionally, the "Tools" button after making a search shows white on hover, with grey text:
![image](https://user-images.githubusercontent.com/4047565/55953206-63ec9200-5c53-11e9-8ce3-fc071d715632.png)

**Comment by belaviyo** [comment]
Thanks for the report. Will be fixed by the next release.
